# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f08e2956a87f7ca2bf439501479d3b1c1acebeb558129fdce0650c141bd88472b701e7c5fe98f4ca1440e29421a472ebd1b473101a9cae34ea453b43ef0660

test:
  secret_key_base: 07a913e280258dc94890de694575e878101cb9677774695f1d119215f2c2ca75e5a6b179f62ec9d567477ad4773605866f8a531b75c05206ffe5e10d4e0541d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
